### ISSUE TITLE
Cannot schedule montly events

### ISSUE THREAD

**Issue by lgrkvst** [AlmostInteractive/node-red-contrib-basic-ical-calendar#2]
I just realised this node is using setInterval to fire triggers. If I wish to trigger on a single monthly event things are going to break: https://stackoverflow.com/questions/12633405/what-is-the-maximum-delay-for-setinterval#:~:text=%22What's%20the%20maximum%20delay%20for,2**32ms%20~%2050%20days.

**Comment by AlmostInteractive** [comment]
https://github.com/AlmostInteractive/node-red-contrib-basic-ical-calendar/blob/2556a935b4ac78355691e72b94e7f0b21f10902f/src/nodes/cal-config.ts#L58C76-L58C79

I do a max cap of two days.  I didn't want to bring in a cron scheduler or write my own so unless there's a big reason to do that, hopefully an update once every two days (instead of once every 30) won't cause any issues.
